// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZtW57zp4n1N28FsmM-kEmxOzyxtmeQSI',
    appId: '1:651005734001:web:d3e5c63218cb33c4cebfd0',
    messagingSenderId: '651005734001',
    projectId: 'cinestream-auth',
    authDomain: 'cinestream-auth.firebaseapp.com',
    storageBucket: 'cinestream-auth.firebasestorage.app',
    measurementId: 'G-N7XEH7VS8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDayfVo4x7mFUGNQv-_ht2yKyHAViM5ZwY',
    appId: '1:651005734001:android:36d4cb61adcc9f43cebfd0',
    messagingSenderId: '651005734001',
    projectId: 'cinestream-auth',
    storageBucket: 'cinestream-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvvOIVkeERs43bX2XUrH_JDv1rv-_iSPo',
    appId: '1:651005734001:ios:0b14a292ddcaf45fcebfd0',
    messagingSenderId: '651005734001',
    projectId: 'cinestream-auth',
    storageBucket: 'cinestream-auth.firebasestorage.app',
    iosBundleId: 'com.example.cinestream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvvOIVkeERs43bX2XUrH_JDv1rv-_iSPo',
    appId: '1:651005734001:ios:0b14a292ddcaf45fcebfd0',
    messagingSenderId: '651005734001',
    projectId: 'cinestream-auth',
    storageBucket: 'cinestream-auth.firebasestorage.app',
    iosBundleId: 'com.example.cinestream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZtW57zp4n1N28FsmM-kEmxOzyxtmeQSI',
    appId: '1:651005734001:web:b1a2cf98d3dd3ae2cebfd0',
    messagingSenderId: '651005734001',
    projectId: 'cinestream-auth',
    authDomain: 'cinestream-auth.firebaseapp.com',
    storageBucket: 'cinestream-auth.firebasestorage.app',
    measurementId: 'G-3C352T64R1',
  );
}
